databases:
  - name: sol-forge-pro-db
    databaseName: solforge_mezx
    plan: free

services:
  - type: web
    runtime: node
    name: solana-gem-scanner-ohio
    plan: free
    region: ohio
    buildCommand: npm install -g pnpm@10.4.1 && pnpm install --frozen-lockfile && pnpm build && pnpm db:push
    startCommand: pnpm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: DATABASE_URL
        fromDatabase:
          name: sol-forge-pro-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: HELIUS_API_KEY
        sync: false
  - type: worker
    runtime: node
    name: solana-gem-scanner-worker-ohio
    plan: starter
    region: ohio
    buildCommand: npm install -g pnpm@10.4.1 && pnpm install --frozen-lockfile && pnpm build && pnpm db:push
    startCommand: pnpm start:worker
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: DATABASE_URL
        fromDatabase:
          name: sol-forge-pro-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: HELIUS_API_KEY
        sync: false
