import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BarChart3, Loader2, Radar, ShieldAlert } from "lucide-react";

export default function Performance() {
  const reportQuery = trpc.scanner.performance.useQuery();
  const report = reportQuery.data;
  return <div dir="rtl" className="scanner-shell"><div className="grid-noise" aria-hidden="true" />
    <header className="scanner-header"><div className="brand-block"><div className="brand-mark"><Radar size={22} /></div><div><p className="eyebrow">SOLANA // PERFORMANCE INTELLIGENCE</p><h1>دقة <span>الإشارات</span></h1></div></div><a href="/" className="back-link"><ArrowRight size={17} />العودة إلى الماسح</a></header>
    <main className="scanner-main performance-page"><section className="alert-banner hud-panel"><ShieldAlert size={24} /><div><strong>قراءة تاريخية، لا تنبؤ</strong><p>التقرير يعرض حركة السعر بعد 24 ساعة من اللقطة الأولى. لا يثبت السببية ولا يحول البيانات إلى توصية أو ضمان نتائج مستقبلية.</p></div></section>
      <section className="performance-hero hud-panel"><div><p className="eyebrow">BACKTEST // 24H SETTLED CHECKPOINTS</p><h2>تقرير معايرة <span>الدرجات</span></h2><p>تسجل الأداة سعر خط الأساس عند ظهور إشارة متوازنة، ثم تقارن السعر بعد 1 ساعة و6 ساعات و24 ساعة. الجدول أدناه يركز على القياسات المكتملة بعد 24 ساعة.</p></div><div className="settled-stat"><BarChart3 /><strong>{report?.totalSettled ?? "—"}</strong><small>قياس 24 ساعة مكتمل</small></div></section>
      {reportQuery.isLoading ? <div className="empty-state"><Loader2 className="animate-spin" />جارٍ تحميل تقرير الأداء…</div> : <section className="accuracy-table hud-panel"><div className="results-header"><div><p className="eyebrow">SCORE CALIBRATION / MANUAL REVIEW</p><h2>الدقة حسب نطاق <span>الفرصة</span></h2></div><div className="fetch-state"><span>حالة البيانات</span><strong>{report?.totalSettled ? "قياسات تاريخية متاحة" : "قيد التراكم"}</strong><small>المعايرة المستقبلية يدوية</small></div></div><div className="table-wrap"><table><thead><tr><th>نطاق الدرجة</th><th>قياسات مكتملة</th><th>ارتفاع سعري</th><th>انخفاض/ثبات</th><th>معدل الارتفاع</th><th>متوسط العائد</th></tr></thead><tbody>{(report?.byBand ?? []).map((band) => <tr key={band.band}><td><strong>{band.band}</strong></td><td>{band.total}</td><td className="up">{band.success}</td><td className="down">{band.failed}</td><td><div className="score-cell"><strong>{band.successRate.toFixed(1)}%</strong><div className="score-track"><i style={{ width: `${band.successRate}%` }} /></div></div></td><td className={band.averageReturn > 0 ? "up" : band.averageReturn < 0 ? "down" : ""}>{band.averageReturn > 0 ? "+" : ""}{band.averageReturn.toFixed(1)}%</td></tr>)}</tbody></table></div>{!report?.totalSettled && <div className="performance-empty"><strong>لا توجد قياسات مكتملة بعد.</strong><p>يحتاج التقرير إلى مرور 24 ساعة على لقطات إشارات مؤهلة. تجمع اللوحة القياسات فقط؛ لا تعدّل أوزان التقييم تلقائياً.</p><Button className="scan-button" asChild><a href="/">العودة إلى الفحص</a></Button></div>}</section>}</main></div>;
}
